port 6379
cluster-enabled yes
cluster-config-file /data/redis/nodes.conf
cluster-node-timeout 500
cluster-require-full-coverage no
cluster-migration-barrier 1
appendonly no
appendfsync no
dir /data/redis
bind 0.0.0.0
protected-mode no
save ""